version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  generate-password:
    lang: python3-http
    handler: ./generate-password
    image: lotfidjermouni/generate-password:latest
    environment:
      DB_HOST: "host.k3d.internal"
      DB_NAME: "mspr_db"
      DB_USER: "mspr_user"
      DB_PORT: "5432"
    secrets:
      - db-creds
      - mfa-key
    build_args:
      ADDITIONAL_PACKAGE: "postgresql-dev gcc musl-dev"

  generate-2fa:
    lang: python3-http
    handler: ./generate-2fa
    image: lotfidjermouni/generate-2fa:latest
    environment:
      DB_HOST: "host.k3d.internal"
      DB_NAME: "mspr_db"
      DB_USER: "mspr_user"
      DB_PORT: "5432"
    secrets:
      - db-creds
      - mfa-key
    build_args:
      ADDITIONAL_PACKAGE: "postgresql-dev gcc musl-dev"

  authenticate-user:
    lang: python3-http
    handler: ./authenticate-user
    image: lotfidjermouni/authenticate-user:latest
    environment:
      DB_HOST: "host.k3d.internal"
      DB_NAME: "mspr_db"
      DB_USER: "mspr_user"
      DB_PORT: "5432"
    secrets:
      - db-creds
      - mfa-key
    build_args:
      ADDITIONAL_PACKAGE: "postgresql-dev gcc musl-dev"